version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: your-app-image
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - .:/app

volumes:
  mongo-data:
